"""Adding new tables

Revision ID: 07a31813e196
Revises: ee4e6e9d9b6f
Create Date: 2024-06-20 10:12:26.949202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07a31813e196'
down_revision = 'ee4e6e9d9b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrients',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sugar_in_g', sa.Float(), nullable=True),
    sa.Column('protein_in_g', sa.Float(), nullable=True),
    sa.Column('sodium_in_mg', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('fat_total_g', sa.Float(), nullable=True),
    sa.Column('fat_saturated_g', sa.Float(), nullable=True),
    sa.Column('potassium_mg', sa.Float(), nullable=True),
    sa.Column('cholesterol_mg', sa.Float(), nullable=True),
    sa.Column('carbohydrates_total_g', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('mealDiary',
    sa.Column('mdid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['patients.pid'], ),
    sa.PrimaryKeyConstraint('mdid')
    )
    op.create_table('mealentry',
    sa.Column('meid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portiontype', sa.String(length=250), nullable=True),
    sa.Column('servingSize', sa.Integer(), nullable=True),
    sa.Column('date_and_time', sa.DateTime(), nullable=True),
    sa.Column('mealtype', sa.Enum('BEVERAGE', 'BREAKFAST', 'LUNCH', 'DINNER', 'BRUNCH', 'SNACK', 'DESSERT', name='mealtype'), nullable=True),
    sa.Column('mealOrDrink', sa.Enum('Food', 'DRINK', 'FOODANDDRINK', name='foodordrink'), nullable=True),
    sa.Column('meal', sa.String(length=250), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('nutrients_id', sa.Integer(), nullable=True),
    sa.Column('mealdiaryid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mealdiaryid'], ['mealDiary.mdid'], ),
    sa.ForeignKeyConstraint(['nutrients_id'], ['nutrients.nid'], ),
    sa.ForeignKeyConstraint(['pid'], ['patients.pid'], ),
    sa.PrimaryKeyConstraint('meid')
    )
    op.create_table('medtime',
    sa.Column('mtid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['medication.mid'], ),
    sa.PrimaryKeyConstraint('mtid')
    )
    with op.batch_alter_table('healthrecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diabetesType', sa.Enum('TYPEONE', 'TYPETWO', name='diabetestype'), nullable=True))

    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendedTime', sa.Enum('AFTERMEAL', 'BEFOREMEAL', name='rectime'), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.drop_column('dosage')
        batch_op.drop_column('frequencyUnit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequencyUnit', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('dosage', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('amount')
        batch_op.drop_column('recommendedTime')

    with op.batch_alter_table('healthrecord', schema=None) as batch_op:
        batch_op.drop_column('diabetesType')

    op.drop_table('medtime')
    op.drop_table('mealentry')
    op.drop_table('mealDiary')
    op.drop_table('nutrients')
    # ### end Alembic commands ###
