"""Made Changes

Revision ID: 862ce5cbb352
Revises: fd9c4efda7af
Create Date: 2024-06-20 17:12:51.948752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '862ce5cbb352'
down_revision = 'fd9c4efda7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('medtime', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medtime', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               existing_nullable=True)

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
