"""Updates

Revision ID: 89e5ca0fb08f
Revises: 7d5068975fd9
Create Date: 2024-06-22 00:23:24.985427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e5ca0fb08f'
down_revision = '7d5068975fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'medication', ['mid'], ['mid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mid')

    # ### end Alembic commands ###
