"""updates

Revision ID: 988e03fdbaaa
Revises: 2487beaf044a
Create Date: 2024-07-08 09:31:08.964060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '988e03fdbaaa'
down_revision = '2487beaf044a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('date_and_time', sa.DateTime(), nullable=True),
    sa.Column('symptom_name', sa.String(length=250), nullable=True),
    sa.Column('symptomType', sa.Enum('MOOD', 'SLEEP', 'APPETITE', 'ACTIVITY', 'OTHER', name='symptomtype'), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('hrid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hrid'], ['healthrecord.hrid'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.pid'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.drop_table('tablename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablename',
    sa.Column('sid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('severity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_and_time', mysql.DATETIME(), nullable=True),
    sa.Column('symptom_name', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('symptomType', mysql.ENUM('MOOD', 'SLEEP', 'APPETITE', 'ACTIVITY', 'OTHER'), nullable=True),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hrid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hrid'], ['healthrecord.hrid'], name='tablename_ibfk_1'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.pid'], name='tablename_ibfk_2'),
    sa.PrimaryKeyConstraint('sid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('symptom')
    # ### end Alembic commands ###
