"""Updated Models

Revision ID: ee4e6e9d9b6f
Revises: ea14d1b03686
Create Date: 2024-06-18 12:36:37.735526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4e6e9d9b6f'
down_revision = 'ea14d1b03686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequencyUnit', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_column('frequencyUnit')

    # ### end Alembic commands ###
