"""Initial migration.

Revision ID: f9752ab1dd2b
Revises: 
Create Date: 2024-06-16 13:17:31.564893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9752ab1dd2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloodsugarlevels',
    sa.Column('bslID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bloodSugarLevel', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=150), nullable=True),
    sa.Column('dateAndTimeRecorded', sa.DateTime(), nullable=True),
    sa.Column('creator', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('hrid', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['hrid'], ['healthrecord.hrid'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.pid'], ),
    sa.PrimaryKeyConstraint('bslID')
    )
    op.create_table('medicationaudit',
    sa.Column('auid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['medication.mid'], ),
    sa.PrimaryKeyConstraint('auid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicationaudit')
    op.drop_table('bloodsugarlevels')
    # ### end Alembic commands ###
